locale: en_UK #Used to determine how numbers need to be formatted when displayed to players
lang:
    prefix: "<#FF8C42>[MMO] "
    bar:
        color: "GREEN"
        style: "PROGRESS"
        format: "<yellow><aqua><talent></aqua> lvl <level> | <aqua><xp></aqua>/<aqua><max_xp>xp</aqua>"
        delay: 200
    messages:
        ability_log: <yellow>Vous avez utilisé <aqua><ability></aqua>, cooldown de <aqua><cooldown> <unit></aqua>
        level-up: <yellow>Vous êtes passé au niveau <aqua><level> <talent></aqua> ! Vous gagnez <aqua><reward></aqua>
        level-up-no-reward: <yellow>Vous êtes passé au niveau <aqua><level> <talent></aqua> !
        xp_up: <yellow>Vous avez gagné <aqua><xp>xp</aqua> en <talent>
        combo_toggle: <yellow>Vous avez <aqua><state></aqua> <yellow>les combos.

#Whether or not to display a boss bar showing player's progression when gaining xp
enable-xp-bar: true
#Whether or not the talents should be enabled
enable-talents: true

talents:
    miner:
        display_name: Miner
        abilities:
            fast-mine:
                display_name: Fast mine
                cooldown: 15
                unit: MINUTES
                level: 15
                effect: default
                log: false
                tiers:
                    - 15
                    - 45
                    - 75
            fast-smelt:
                display_name: Fast smelt
                cooldown: 1
                unit: HOURS
                level: 85
                effect: default
                log: true
            minecraft-exp-multiplier:
                display_name: Minecraft xp multiplier
                cooldown: 1
                unit: SECONDS
                level: 5
                effect: default
                log: false
            magnetic-field:
                display_name: Magnetic field
                cooldown: 30
                unit: MINUTES
                level: 35
                effect: default
                log: true
                tiers:
                    - 35
                    - 65
                    - 95
        combo_items:
            - DIAMOND_PICKAXE
            - IRON_PICKAXE
            - STONE_PICKAXE
            - GOLDEN_PICKAXE
            - WOODEN_PICKAXE
            - NETHERITE_PICKAXE
    hunter:
        display_name: Hunter
        abilities:
            dodging:
                display_name: Dodging
                cooldown: 5
                unit: MINUTES
                level: 25
                effect: trail
                log: true
                tiers:
                  - 25
                  - 60
                  - 95
            exp-in-bottle:
                display_name: Xp in bottle
                cooldown: 0
                unit: SECONDS
                level: 5
                effect: default
                log: false
                tiers:
                  - 5
                  - 30
                  - 40
            fire-bow:
                display_name: Fire bow
                cooldown: 15
                unit: MINUTES
                level: 15
                effect: default
                log: true
                tiers:
                  - 15
                  - 30
                  - 70
            hiding:
                display_name: Hiding
                cooldown: 25
                unit: SECONDS
                level: 50
                effect: default
                log: true
                tiers:
                  - 50
                  - 85
                  - 100
        combo_items:
            - DIAMOND_SWORD
            - IRON_SWORD
            - STONE_SWORD
            - GOLDEN_SWORD
            - WOODEN_SWORD
            - NETHERITE_SWORD
    farmer:
        display_name: Farmer
        abilities:
            nature-touch:
                display_name: Nature touch
                cooldown: 15
                unit: MINUTES
                level: 5
                effect: default
                log: false
                tiers:
                  - 5
                  - 30
                  - 70
            better-bonemeal:
                display_name: Better bonemeal
                cooldown: 0
                unit: SECONDS
                level: 15
                effect: default
                log: true
                tiers:
                  - 15
                  - 45
                  - 100
            animal-twins:
                display_name: Animal twins
                cooldown: 1
                unit: SECONDS
                level: 20
                effect: default
                log: false
                tiers:
                  - 20
                  - 55
                  - 80
            tasty-bread:
                display_name: Tasty bread
                cooldown: 1
                unit: SECONDS
                level: 10
                effect: default
                log: false
                tiers:
                  - 10
                  - 60
        combo_items:
            - DIAMOND_HOE
            - IRON_HOE
            - STONE_HOE
            - GOLDEN_HOE
            - WOODEN_HOE
            - NETHERITE_HOE
    lumberjack:
        display_name: Lumberjack
        abilities:
            double-drop-log:
                display_name: Double drop log
                cooldown: 0
                unit: SECONDS
                level: 5
                effect: default
                log: false
                tiers:
                  - 5
                  - 40
                  - 75
            better-apple-drop:
                display_name: Better apple drop
                cooldown: 0
                unit: SECONDS
                level: 5
                effect: default
                log: false
                tiers:
                  - 5
                  - 40
                  - 75
            timber:
                display_name: Timber!!!
                cooldown: 5
                unit: MINUTES
                level: 35
                effect: default
                log: true
                tiers:
                  - 35
                  - 65
                  - 95
            strip:
                display_name: Strip
                cooldown: 10
                unit: MINUTES
                level: 50
                effect: default
                log: true
            thick-tree:
                display_name: Thick tree
                cooldown: 15
                unit: MINUTES
                level: 10
                effect: default
                log: true
        combo_items:
            - DIAMOND_AXE
            - IRON_AXE
            - STONE_AXE
            - GOLDEN_AXE
            - WOODEN_AXE
            - NETHERITE_AXE

talent-grinding:
    miner:
        break:
            NETHERRACK: 0.5
            STONE: 0.75
            DIORITE: 1.5
            ANDESITE: 1.5
            GRANITE: 1.5
            TERRACOTTA: 1.5
            BROWN_TERRACOTTA: 1.5
            WHITE_TERRACOTTA: 1.5
            LIGHT_GRAY_TERRACOTTA: 1.5
            YELLOW_TERRACOTTA: 1.5
            ORANGE_TERRACOTTA: 1.5
            RED_TERRACOTTA: 1.5
            DEEPSLATE: 3
            CALCITE: 3
            TUFF: 3
            DRIPSTONE_BLOCK: 3
            BASALT: 0.75
            END_STONE: 3
            BLACKSTONE: 4
            COAL_ORE: 6
            COPPER_ORE: 6
            IRON_ORE: 6
            NETHER_QUARTZ_ORE: 6
            NETHER_GOLD_ORE: 6
            AMETHYST_BLOCK: 2.5
            AMETHYST_CLUSTER: 2
            GOLD_ORE: 12
            REDSTONE_ORE: 12
            LAPIS_ORE: 12
            OBSIDIAN: 16
            DIAMOND_ORE: 24
            EMERALD_ORE: 32
            ANCIENT_DEBRIS: 48

            DEEPSLATE_COAL_ORE: 7
            DEEPSLATE_COPPER_ORE: 7
            DEEPSLATE_IRON_ORE: 7
            DEEPSLATE_GOLD_ORE: 13
            DEEPSLATE_REDSTONE_ORE: 13
            DEEPSLATE_LAPIS_ORE: 13
            DEEPSLATE_DIAMOND_ORE: 25
            DEEPSLATE_EMERALD_ORE: 33
        first_craft:
            IRON_PICKAXE: 50
            DIAMOND_PICKAXE: 100
            NETHERITE_PICKAXE: 200
    lumberjack:
        break:
            OAK_LEAVES: 0.1
            SPRUCE_LEAVES: 0.1
            JUNGLE_LEAVES: 0.1
            DARK_OAK_LEAVES: 0.1
            BIRCH_LEAVES: 0.1
            ACACIA_LEAVES: 0.1
            AZALEA_LEAVES: 0.1
            FLOWERING_AZALEA_LEAVES: 1
            SPRUCE_LOG: 3
            SPRUCE_WOOD: 3
            JUNGLE_LOG: 3
            JUNGLE_WOOD: 3
            DARK_OAK_LOG: 4
            DARK_OAK_WOOD: 4
            MANGROVE_LOG: 4
            MANGROVE_ROOTS: 4
            OAK_LOG: 5
            OAK_WOOD: 5
            BIRCH_LOG: 5
            BIRCH_WOOD: 5
            ACACIA_LOG: 5
            RED_MUSHROOM_BLOCK: 6
            BROWN_MUSHROOMS_BLOCK: 6
            MUSHROOM_STEM: 6
            WARPED_STEM: 7
            WARPED_FUNGUS: 7
            WARPED_WART_BLOCK: 1
            NETHER_WART_BLOCK: 1
            VINE: 2
            TWISTING_VINES: 3
            WEEPING_VINES: 3
        first_craft:
            IRON_AXE: 50
            DIAMOND_AXE: 100
            NETHERITE_AXE: 200
    hunter:
        kill:
            ZOMBIE: 1.5
            ZOMBIE_VILLAGER: 3
            HUSK: 4
            SKELETON: 1.5
            STRAY: 4
            CREEPER: 2
            DROWNED: 2.25
            ENDERMAN: 0.5
            ENDERMITE: 7
            WITCH: 5
            WITHER_SKELETON: 4
            PHANTOM: 3
            GUARDIAN: 5
            ELDER_GUARDIAN: 10
            EVOKER: 6
            GHAST: 5
            HOGLIN: 3
            MAGMA_CUBE: 1
            PIGLIN_BRUTE: 6
            PIGLIN: 2
            ZOMBIFIED_PIGLIN: 4
            RAVAGER: 8
            SILVERFISH: 1
            SHULKER: 5
            PILLAGER: 3
            SLIME: 0.5
            VEX: 2
            VINDICATOR: 4
            ZOGLIN: 6
            ENDER_DRAGON: 150
            WITHER: 50
            CAVE_SPIDER: 1
            SPIDER: 1
            BLAZE: 2
        first_craft:
            IRON_SWORD: 50
            DIAMOND_SWORD: 100
            NETHERITE_SWORD: 200
    farmer:
        break:
            WHEAT: 2.5
            BEETROOT_SEEDS: 2.5
            POTATOES: 2.5
            CARROTS: 2.5
            NETHER_WART: 2.5
            SWEET_BERRIES: 2.5
            COCOA_BEANS: 2.5
            MELON: 3
            PUMPKIN: 3
            BAMBOO: 2
            SUGAR_CANE: 2
            CACTUS: 2
            KELP: 2
            CRIMSON_FUNGUS: 4
            WARPED_FUNGUS: 4
            SEA_PICKLE: 4
            BROWN_MUSHROOM: 6
            RED_MUSHROOM: 6
            CHORUS_FLOWER: 8
        first_craft:
            IRON_HOE: 50
            DIAMOND_HOE: 100
            NETHERITE_HOE: 200


#Define money rewards when a player levels up in one talent
level-up-rewards:
    miner:
#       "level": reward # "*" means every levels, its stacked with the specific level reward 
        "*": 1.25% #If you add a %, the money given will be the percentage of the xp required to reach this level from the previous one
        "50": 30
rewards-rounding-method: no # Round rewards defined above, accepted values no, closest, up, down

blockus-ignored-blocks:
    - CARROTS
    - WHEAT
    - POTATOES
    - BEETROOTS