locale: en_UK #Used to determine how numbers need to be formatted when displayed to players
lang:
    prefix: "<#FF8C42>[MMO] "
    bar:
        color: "GREEN"
        style: "PROGRESS"
        format: "<yellow><aqua><talent></aqua> lvl <level> | <aqua><xp></aqua>/<aqua><max_xp>xp</aqua>"
        delay: 200
    messages:
        ability_log: <yellow>Vous avez utilisé <aqua><ability></aqua>, cooldown de <aqua><cooldown> <unit></aqua>
        level-up: <yellow>Vous êtes passé au niveau <aqua><level> <talent></aqua> ! Vous gagnez <aqua><reward></aqua>
        level-up-no-reward: <yellow>Vous êtes passé au niveau <aqua><level> <talent></aqua> !
        level-up-title: <bold><gradient:yellow:green>↑ LEVEL UP ↑
        level-up-subtitle: <aqua>Niveau <level> <talent>
        ability-unlocked: <yellow>Habilité <aqua><ability></aqua> débloquée !
        ability-upgrade: <yellow>Habilité <aqua><ability></aqua> améliorée au <aqua>Tier <tier></aqua> !
        xp_up: <yellow>+<aqua><xp>xp</aqua> en <talent>
        xp_up_boost: <bold><aqua> BOOST x<boost></aqua></bold>
        combo_toggle: <yellow>Vous avez <aqua><state></aqua> les combos.
    xp_boost:
        bar_title: "<aqua><bold>XP Boost x<boost></bold> <yellow>-</yellow> <talent> <yellow>-</yellow> <author> <yellow>-</yellow> <time></aqua>"
        notif: "<yellow><aqua><author></aqua> vient d'activer un boost <aqua><bold>x<boost></bold></aqua> pour le métier <aqua><talent></aqua> !"
    ability-use-cooldown: <gold>You must wait <gray><duration> <unit></gray> before using <aqua><ability></aqua>.

    combo:
        delimiter: " - "
        empty: "<gray>?</gray>"
        # Names matching the ComboKey enum in lowercase.
        left: "<gold>G</gold>"
        right: "<gold>D</gold>"
        shift: "<gold>S</gold>"
#Whether or not to display a boss bar showing player's progression when gaining xp
enable-xp-bar: true
#Whether or not the talents should be enabled
enable-talents: true

talents:
    miner:
        display_name: ⛏ Mineur
        abilities:
            fast-mine:
                display_name: Pioche Aiguisée
                display_item: GOLDEN_PICKAXE
                description: Donne célérité
                cooldown: 15
                unit: MINUTES
                level: 15
                effect: default
                log: false
                tiers:
                    - 15
                    - 45
                    - 75
            fast-smelt:
                display_name: Cuisson Instantanée
                display_item: FURNACE
                description: Cuit le contenu d'un four instantanément
                instruction: Clique gauche sur un haut fourneau avec du charbon
                cooldown: 30
                unit: MINUTES
                level: 85
                effect: default
                log: true
            minecraft-exp-multiplier:
                display_name: Brossage Minutieux
                display_item: EXPERIENCE_BOTTLE
                description: Donne davantage d'XP en récoltant des minerais
                instruction: Passif
                cooldown: 1
                unit: SECONDS
                level: 5
                effect: default
                log: false
            magnetic-field:
                display_name: Champ Magnétique
                display_item: COMPASS
                description: Donne une surbrillance aux minerais alentour
                instruction: Accroupi + clique droit avec une boussole
                cooldown: 30
                unit: MINUTES
                level: 35
                effect: default
                log: true
                tiers:
                    - 35
                    - 65
                    - 95
        combo_items:
            - DIAMOND_PICKAXE
            - IRON_PICKAXE
            - STONE_PICKAXE
            - GOLDEN_PICKAXE
            - WOODEN_PICKAXE
            - NETHERITE_PICKAXE
    hunter:
        display_name: 🗡 Chasseur
        abilities:
            dodging:
                display_name: Bélier
                display_item: GOAT_HORN
                description: Projection rapide, fait des dégâts sur son passage
                instruction: Combo G - G - D
                cooldown: 5
                unit: MINUTES
                level: 25
                effect: trail
                log: true
                tiers:
                    - 25
                    - 60
                    - 95
            exp-in-bottle:
                display_name: Mise en Bouteille
                display_item: EXPERIENCE_BOTTLE
                description: Mets de l'experience dans une bouteille
                instruction: Accroupi + clique droit avec une fiole vide
                cooldown: 0
                unit: SECONDS
                level: 5
                effect: default
                log: false
                tiers:
                    - 5
                    - 30
                    - 40
            fire-bow:
                display_name: Flèche Enflammée
                display_item: BOW
                description: Lance une flèche enflammée, fait des dégâts à l'atterissage
                instruction: Combo D - G - G puis tirer avec un arc enchanté Flamme
                cooldown: 15
                unit: MINUTES
                level: 15
                effect: default
                log: true
                tiers:
                    - 15
                    - 30
                    - 70
            hiding:
                display_name: Camouflage
                display_item: GLASS
                description: Rend le joueur invisible
                instruction: Combo G - D - D
                cooldown: 25
                unit: MINUTES
                level: 50
                effect: default
                log: true
                tiers:
                    - 50
                    - 85
                    - 100
        combo_items:
            - DIAMOND_SWORD
            - IRON_SWORD
            - STONE_SWORD
            - GOLDEN_SWORD
            - WOODEN_SWORD
            - NETHERITE_SWORD
    farmer:
        display_name: ✂ Fermier
        abilities:
            nature-touch:
                display_name: Jeunes Pousses
                display_item: WHEAT_SEEDS
                description: Replante les cultures automatiquement après leur récolte
                instruction: Passif
                cooldown: 15
                unit: MINUTES
                level: 5
                effect: default
                log: false
                tiers:
                    - 5
                    - 30
                    - 70
            better-bonemeal:
                display_name: Engrais Naturel
                display_item: BONE_MEAL
                description: Fais pousser tout ce qu'il y a autour du joueur
                instruction: Accroupi + clique droit avec de la poudre d'os
                cooldown: 15
                unit: MINUTES
                level: 15
                effect: default
                log: true
                tiers:
                    - 15
                    - 45
                    - 100
            animal-twins:
                display_name: Jumeaux
                display_item: WHEAT
                description: Donne des jumeaux à la reproduction
                instruction: Passif
                cooldown: 1
                unit: SECONDS
                level: 20
                effect: default
                log: false
                tiers:
                    - 20
                    - 55
                    - 80
            tasty-bread:
                display_name: Pain Aléchant
                display_item: BREAD
                description: Tout les animaux deviennent attirés par le pain
                instruction: Passif
                cooldown: 1
                unit: SECONDS
                level: 10
                effect: default
                log: false
                tiers:
                    - 10
                    - 60
        combo_items:
            - DIAMOND_HOE
            - IRON_HOE
            - STONE_HOE
            - GOLDEN_HOE
            - WOODEN_HOE
            - NETHERITE_HOE
    lumberjack:
        display_name: 🪓 Bûcheron
        abilities:
            double-drop-log:
                display_name: Grosses Bûches
                display_item: OAK_LOG
                description: Double le drop de bûches et pommes
                instruction: Passif
                cooldown: 0
                unit: SECONDS
                level: 5
                effect: default
                log: false
                tiers:
                    - 5
                    - 40
                    - 75
            timber:
                display_name: Timber
                display_item: GOLDEN_AXE
                description: Bûches adjacentes sont cassées
                instruction: Combo G - G - G
                cooldown: 5
                unit: MINUTES
                level: 35
                effect: default
                log: true
                tiers:
                    - 35
                    - 65
                    - 95
            strip:
                display_name: Écorçage
                display_item: STRIPPED_OAK_LOG
                description: Ecorce les bûches adjacentes
                instruction: Accroupi + clique gauche sur une bûche
                cooldown: 10
                unit: MINUTES
                level: 50
                effect: default
                log: true
            thick-tree:
                display_name: Haricot Magique
                display_item: JUNGLE_SAPLING
                description: Fait pousser un grand arbre (Acajou, Sapin, Chêne noir) avec une seule pousse
                instruction: Combo D - D - G
                cooldown: 15
                unit: MINUTES
                level: 10
                effect: default
                log: true
        combo_items:
            - DIAMOND_AXE
            - IRON_AXE
            - STONE_AXE
            - GOLDEN_AXE
            - WOODEN_AXE
            - NETHERITE_AXE

talent-grinding:
    miner:
        break:
            NETHERRACK: 0.25
            STONE: 0.75
            DIORITE: 1.5
            ANDESITE: 1.5
            GRANITE: 1.5
            TERRACOTTA: 1.5
            BROWN_TERRACOTTA: 1.5
            WHITE_TERRACOTTA: 1.5
            LIGHT_GRAY_TERRACOTTA: 1.5
            YELLOW_TERRACOTTA: 1.5
            ORANGE_TERRACOTTA: 1.5
            RED_TERRACOTTA: 1.5
            DEEPSLATE: 3
            CALCITE: 5
            TUFF: 2.5
            DRIPSTONE_BLOCK: 3
            BASALT: 0.75
            SMOOTH_BASALT: 5
            END_STONE: 3
            BLACKSTONE: 2.75
            GILDED_BLACKSTONE: 15
            COAL_ORE: 6
            COPPER_ORE: 6
            IRON_ORE: 6
            NETHER_QUARTZ_ORE: 6
            NETHER_GOLD_ORE: 6
            AMETHYST_BLOCK: 2.5
            AMETHYST_CLUSTER: 2
            GOLD_ORE: 12
            REDSTONE_ORE: 12
            LAPIS_ORE: 12
            OBSIDIAN: 10
            DIAMOND_ORE: 27
            EMERALD_ORE: 32
            ANCIENT_DEBRIS: 48

            DEEPSLATE_COAL_ORE: 8
            DEEPSLATE_COPPER_ORE: 7
            DEEPSLATE_IRON_ORE: 7
            DEEPSLATE_GOLD_ORE: 13
            DEEPSLATE_REDSTONE_ORE: 13
            DEEPSLATE_LAPIS_ORE: 13
            DEEPSLATE_DIAMOND_ORE: 24
            DEEPSLATE_EMERALD_ORE: 33
        first_craft:
            IRON_PICKAXE: 50
            DIAMOND_PICKAXE: 100
            NETHERITE_PICKAXE: 200
    lumberjack:
        break:
            OAK_LEAVES: 0.1
            SPRUCE_LEAVES: 0.1
            JUNGLE_LEAVES: 0.1
            DARK_OAK_LEAVES: 0.1
            BIRCH_LEAVES: 0.1
            ACACIA_LEAVES: 0.1
            AZALEA_LEAVES: 0.1
            MANGROVE_LEAVES: 0.1
            FLOWERING_AZALEA_LEAVES: 1
            SPRUCE_LOG: 3
            SPRUCE_WOOD: 3
            JUNGLE_LOG: 3
            JUNGLE_WOOD: 3
            DARK_OAK_LOG: 4
            DARK_OAK_WOOD: 4
            MANGROVE_LOG: 6
            MANGROVE_ROOTS: 2.5
            OAK_LOG: 5
            OAK_WOOD: 5
            BIRCH_LOG: 5
            BIRCH_WOOD: 5
            ACACIA_LOG: 5
            RED_MUSHROOM_BLOCK: 1
            BROWN_MUSHROOM_BLOCK: 1
            MUSHROOM_STEM: 1
            WARPED_STEM: 2
            WARPED_FUNGUS: 2
            WARPED_WART_BLOCK: 1
            NETHER_WART_BLOCK: 1
            VINE: 2
            TWISTING_VINES: 2
            TWISTING_VINES_PLANT: 2
            WEEPING_VINES: 2
            WEEPING_VINES_PLANT: 2
            # with berries
            CAVE_VINES_PLANT: 4
        first_craft:
            IRON_AXE: 50
            DIAMOND_AXE: 100
            NETHERITE_AXE: 200
    hunter:
        kill:
            ZOMBIE: 8
            ZOMBIE_VILLAGER: 10
            HUSK: 12
            SKELETON: 8
            STRAY: 5.75
            CREEPER: 10
            DROWNED: 3.25
            ENDERMAN: 0.5
            ENDERMITE: 9
            WITCH: 12
            WITHER_SKELETON: 13
            PHANTOM: 8
            GUARDIAN: 10
            ELDER_GUARDIAN: 15
            EVOKER: 2.5
            GHAST: 11
            HOGLIN: 9.5
            MAGMA_CUBE: 5.5
            PIGLIN_BRUTE: 14
            PIGLIN: 9
            ZOMBIFIED_PIGLIN: 1.5
            RAVAGER: 15
            SILVERFISH: 6.5
            SHULKER: 10
            PILLAGER: 6
            SLIME: 6
            VEX: 4
            VINDICATOR: 4
            ZOGLIN: 6
            ENDER_DRAGON: 150
            WITHER: 50
            WARDEN: 170
            CAVE_SPIDER: 10
            SPIDER: 8.5
            BLAZE: 8
        first_craft:
            IRON_SWORD: 50
            DIAMOND_SWORD: 100
            NETHERITE_SWORD: 200
    farmer:
        break:
            WHEAT: 4
            BEETROOT_SEEDS: 4
            POTATOES: 4
            CARROTS: 4
            NETHER_WART: 4
            SWEET_BERRIES: 4
            COCOA_BEANS: 4
            MELON: 3
            PUMPKIN: 3
            BAMBOO: 2
            SUGAR_CANE: 2
            CACTUS: 2
            KELP: 2
            CRIMSON_FUNGUS: 4
            WARPED_FUNGUS: 4
            SEA_PICKLE: 2.75
            BROWN_MUSHROOM: 1
            RED_MUSHROOM: 1
            CHORUS_FLOWER: 3
        breed:
            HORSE: 2
            DONKEY: 3
            COW: 1
            GOAT: 4
            MOOSHROOM: 5
            SHEEP: 1
            PIG: 1
            CHICKEN: 0.5
            WOLF: 2
            CAT: 2
            OCELOT: 3
            AXOLOTL: 4
            LLAMA: 2
            RABBIT: 2
            TURTLE: 3
            PANDA: 4
            FOX: 4
            BEE: 2
            STRIDER: 4
            HOGLIN: 4
            FROG: 3
        first_craft:
            IRON_HOE: 50
            DIAMOND_HOE: 100
            NETHERITE_HOE: 200

#Define money rewards when a player levels up in one talent
level-up-rewards:
    miner:
        #       "level": reward # "*" means every levels, its stacked with the specific level reward
        "*": 1.0% #If you add a %, the money given will be the percentage of the xp you have accumulated over time
        "50": 30
rewards-rounding-method: "no" # Round rewards defined above, accepted values no, closest, up, down

blockus-ignored-blocks:
    - CARROTS
    - WHEAT
    - POTATOES
    - BEETROOTS
ageable-ignored-blocks:
    - TWISTING_VINES_PLANT
    - TWISTING_VINES
    - WEEPING_VINES_PLANT
    - WEEPING_VINES
    - SUGAR_CANE
# This will subtract the specified xp from the xp given by mobs originating from spawners
decrease-spawner-mobs-by:
#    "*": 5.0 # Will subtract 5 xp to every spawner mobs
#   "SPIDER": 1.5 # This has priority over the global selector "*"

palier-coloration:
    - "#5EBD3E"
    - "#FFB900"
    - "#F78200"
    - "#E23838"
    - "#973999"

max-talent-level: 100

talent-tree:
    title: <talent> <player>
    # Placeholders: talent, level, xp
    talent-item:
        name: <bold><aqua><talent>
        lore:
            - <yellow>Niveau <aqua><level></aqua>
            - <yellow>XP <aqua><xp></aqua>
    # Placeholders: ability, tier, description, cooldown-value, cooldown-unit, required-level
    ability-item:
        name: <bold><yellow><ability>
        with-tier: <aqua> <tier>
        lore:
            - <gray><description>
            - <dark_purple><instruction>
            - ""
            - <yellow>Cooldown <aqua><cooldown-value> <cooldown-unit>
            - "<is-unlocked-color>[Niveau <required-level>]"
