lang:
    prefix: "<#FF8C42>[MMO] "
    bar:
        color: "GREEN"
        style: "PROGRESS"
        format: "<yellow><aqua><talent></aqua> lvl <level> | <aqua><xp></aqua>/<aqua><max_xp>xp</aqua>"
        delay: 200
    messages:
        ability_log: <yellow>Vous avez utilisé <aqua><ability></aqua>, cooldown de <aqua><cooldown> <unit></aqua>
        level_up: <yellow>Vous êtes passé au niveau <aqua><level> <talent></aqua> ! Vous gagnez <aqua><reward></aqua>
        xp_up: <yellow>Vous avez gagné <aqua><xp>xp</aqua> en <talent>
        combo_toggle: <yellow>Vous avez <aqua><state></aqua> <yellow>les combos.

#Whether or not to display a boss bar showing player's progression when gaining xp
enable-xp-bar: true
#Whether or not the talents should be enabled
enable-talents: true

talents:
    miner:
        display_name: Miner
        abilities:
            fast-mine:
                display_name: Fast mine
                cooldown: 15
                unit: MINUTES
                level: 15
                effect: default
                log: false
                tiers:
                    - 15
                    - 45
                    - 75
            fast-smelt:
                display_name: Fast smelt
                cooldown: 1
                unit: HOURS
                level: 85
                effect: default
                log: true
            minecraft-exp-multiplier:
                display_name: Minecraft xp multiplier
                cooldown: 1
                unit: SECONDS
                level: 5
                effect: default
                log: false
            magnetic-field:
                display_name: Magnetic field
                cooldown: 30
                unit: MINUTES
                level: 35
                effect: default
                log: true
                tiers:
                    - 35
                    - 65
                    - 95
        combo_items:
            - DIAMOND_PICKAXE
            - IRON_PICKAXE
            - STONE_PICKAXE
            - GOLDEN_PICKAXE
            - WOODEN_PICKAXE
            - NETHERITE_PICKAXE
    hunter:
        display_name: Hunter
        abilities:
            dodging:
                display_name: Dodging
                cooldown: 1
                unit: SECONDS
                level: 5
                effect: trail
                log: true
            xp-in-bottle:
                display_name: Xp in bottle
                cooldown: 4
                unit: SECONDS
                level: 10
                effect: default
                log: false
            fire-bow:
                display_name: Fire bow
                cooldown: 3
                unit: SECONDS
                level: 3
                effect: default
                log: true
            hiding:
                display_name: Hiding
                cooldown: 1
                unit: SECONDS
                level: 3
                effect: default
                log: true
        combo_items:
            - DIAMOND_SWORD
            - IRON_SWORD
            - STONE_SWORD
            - GOLDEN_SWORD
            - WOODEN_SWORD
            - NETHERITE_SWORD
    farmer:
        display_name: Farmer
        abilities:
            nature-touch:
                display_name: Nature touch
                cooldown: 1
                unit: SECONDS
                level: 3
                effect: default
                log: false
            better-bonemeal:
                display_name: Better bonemeal
                cooldown: 1
                unit: SECONDS
                level: 3
                effect: default
                log: true
            animal-twins:
                display_name: Animal twins
                cooldown: 1
                unit: SECONDS
                level: 3
                effect: default
                log: false
            tasty-bread:
                display_name: Tasty bread
                cooldown: 1
                unit: SECONDS
                level: 3
                effect: default
                log: false
        combo_items:
            - DIAMOND_HOE
            - IRON_HOE
            - STONE_HOE
            - GOLDEN_HOE
            - WOODEN_HOE
            - NETHERITE_HOE
    lumberjack:
        display_name: Lumberjack
        abilities:
            double-drop-log:
                display_name: Double drop log
                cooldown: 0
                unit: SECONDS
                level: 3
                effect: default
                log: false
            better-apple-drop:
                display_name: Better apple drop
                cooldown: 0
                unit: SECONDS
                level: 3
                effect: default
                log: false
            timber:
                display_name: Timber!!!
                cooldown: 1
                unit: SECONDS
                level: 3
                effect: default
                log: true
            strip:
                display_name: Strip
                cooldown: 1
                unit: SECONDS
                level: 3
                effect: default
                log: true
            thick-tree:
                display_name: Thick tree
                cooldown: 1
                unit: SECONDS
                level: 3
                effect: default
                log: true
        combo_items:
            - DIAMOND_AXE
            - IRON_AXE
            - STONE_AXE
            - GOLDEN_AXE
            - WOODEN_AXE
            - NETHERITE_

talent-grinding:
    miner:
        break:
            NETHERRACK: 0.5
            STONE: 1
            DIORITE: 1.5
            ANDESITE: 1.5
            GRANITE: 1.5
            TERRACOTTA: 1.5
            BROWN_TERRACOTTA: 1.5
            WHITE_TERRACOTTA: 1.5
            LIGHT_GRAY_TERRACOTTA: 1.5
            YELLOW_TERRACOTTA: 1.5
            ORANGE_TERRACOTTA: 1.5
            RED_TERRACOTTA: 1.5
            DEEPSLATE: 3
            CALCITE: 3
            TUFF: 3
            DRIPSTONE_BLOCK: 3
            BASALT: 3
            END_STONE: 3
            BLACKSTONE: 4
            COAL_ORE: 6
            COPPER_ORE: 6
            IRON_ORE: 6
            NETHER_QUARTZ_ORE: 6
            NETHER_GOLD_ORE: 6
            AMETHYST_BLOCK: 10
            AMETHYST_CLUSTER: 10
            GOLD_ORE: 12
            REDSTONE_ORE: 12
            LAPIS_ORE: 12
            OBSIDIAN: 16
            DIAMOND_ORE: 24
            EMERALD_ORE: 32
            ANCIENT_DEBRIS: 48

            DEEPSLATE_COAL_ORE: 7
            DEEPSLATE_COPPER_ORE: 7
            DEEPSLATE_IRON_ORE: 7
            DEEPSLATE_GOLD_ORE: 13
            DEEPSLATE_REDSTONE_ORE: 13
            DEEPSLATE_LAPIS_ORE: 13
            DEEPSLATE_DIAMOND_ORE: 25
            DEEPSLATE_EMERALD_ORE: 33

        craft:
            NETHERITE_PICKAXE: 5

        first_craft:
            DIAMOND_PICKAXE: 100
            IRON_PICKAXE: 50
            STONE_PICKAXE: 25
            WOODEN_PICKAXE: 10
