name: LaBoulangerieMmo
version: ${project.version}
main: fr.laboulangerie.laboulangeriemmo.LaBoulangerieMmo
api-version: 1.16
authors: [ TheHunter365, Grooble_ ]
depend: [ProtocolLib]
commands:
  stats:
    permission: laboulangeriemmo.stats
    description: See your level and other information
    usage: /stats [player]
  mmo:
    permission: laboulangeriemmo.mmo
    description: Admin command
    usage: /mmo xp <player> [see|add|subtract] <talent> ?[amount]
permissions:
  laboulangeriemmo.stats:
    default: true
  laboulangeriemmo.stats.see:
    default: op
  laboulangeriemmo.mmo:
    default: op
  laboulangeriemmo.*:
    default: op
    children:
      laboulangeriemmo.stats: true
      laboulangeriemmo.stats.see: true
      laboulangeriemmo.mmo: true