name: LaBoulangerieMmo
version: 2.2.3
main: net.laboulangerie.laboulangeriemmo.LaBoulangerieMmo
api-version: 1.19
authors: [TheHunter365, Grooble_, Pikachuz3, PainOchoco, BlackoutBurst, SunshineDev]
depend: [ProtocolLib, Vault]
softdepend: [PlaceholderAPI, Towny, BetonQuest, WorldGuard, MythicMobs]
commands:
    stats:
        permission: laboulangeriemmo.stats
        description: See your level and other information
        usage: /stats <player>|[leaderboard] <talent>
    mmo:
        permission: laboulangeriemmo.mmo
        description: Admin command
        usage: /mmo [xp|reload|blockus|xpboost] <player>|[isBlockus|mark|unmark] [see|add|subtract] <talent> ?[amount]
    combo:
        permission: laboulangeriemmo.combo
        description: Toggle on/off the combo system
        usage: /combo ?[on|off|toggle]
    talent:
        permission: laboulangeriemmo.talent
        description: View talent's abilities and tier progression
        usage: /talent <talent>
    townymmo:
permissions:
    laboulangeriemmo.stats:
        default: true
    laboulangeriemmo.combo:
        default: true
    laboulangeriemmo.stats.see:
        default: op
    laboulangeriemmo.mmo:
        default: op
    laboulangeriemmo.*:
        default: op
        children:
            laboulangeriemmo.stats: true
            laboulangeriemmo.stats.see: true
            laboulangeriemmo.mmo: true
            laboulangeriemmo.combo: true
