name: LaBoulangerieMmo continuous delivery

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDk 1.17 setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.1.3
        with:
         gradle-version: "7.4.1"
         arguments: assemble
      - uses: actions/upload-artifact@v1
        with:
          name: laboulangeriemmo
          path: build/libs/LaBoulangerieMmo.jar
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: laboulangeriemmo
      - name: Clone Plugins Project
        run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name "${{ secrets.GH_USER }}"
          git clone https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/LaBoulangerie/Plugins.git
          cp **.jar Plugins/
          cd Plugins/
          git add .
          git commit -m "workflow $GITHUB_RUN_ID from $GITHUB_REPOSITORY"
          git push https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/LaBoulangerie/Plugins.git HEAD:master
