name: LaBoulangerieMmo continuous delivery

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDk 1.21 setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.21
      - uses: actions/cache@v3
        env:
          cache-name: cache-gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/caches
          key: ${{ runner.os }}-gradle-${{ env.cache-name }}-${{ hashFiles('*.gradle.kts', '**/gradle-wrapper.properties') }}
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.1.3
        with:
         gradle-version: "8.11.1"
         arguments: assemble
      - name: Clean build outputs
        run: rm build/libs/LaBoulangerieMmo-*dev*.jar
      - uses: actions/upload-artifact@v4
        with:
          name: laboulangeriemmo
          path: build/libs/
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: laboulangeriemmo
      - name: Clone Plugins Project
        run: |
          git config --global user.name "octocroissant[bot]"
          git config --global user.email 149737708+octocroissant[bot]@users.noreply.github.com
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git clone https://octocroissant[bot]:${{ secrets.PAT_TOKEN }}@github.com/LaBoulangerie/Server.git
          mv *.jar LaBoulangerieMmo.jar
          cp **.jar Server/plugins/
          cd Server
          git add .
          git commit -m "Update artifact from $GITHUB_REPOSITORY"
          git push
