name: LaBoulangerieMmo continuous delivery

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDk 1.16 setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.16
      - name: Maven build
        run: mvn clean package
      - uses: actions/upload-artifact@v1
        with:
          name: laboulangeriemmo
          path: target
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Clone Plugins Project
        run: |
          git clone https://$GH_USER:$GH_TOKEN@github.com/LaBoulangerie/Plugins.git &> /dev/null
          cp ./target/*.jar Plugins/
          cd Plugins/
          git add .
          git commit -m "${{ github.job }} from ${{ github.repository }}
          git push
