name: LaBoulangerieMmo continuous delivery

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache m2 repository
        uses: actions/cache@v2
        env:
          cache-name: cache-m2-repository
        with:
          path: ~/.m2
          key: ${{ github.repository }}-build-${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
      - name: JDk 1.16 setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.16
      - name: Maven build
        run: mvn clean package
      - uses: actions/upload-artifact@v1
        with:
          name: laboulangeriemmo
          path: target
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: laboulangeriemmo
      - name: Clone Plugins Project
        run: |
          git clone https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/LaBoulangerie/Plugins.git
          cp ./target/*.jar Plugins/
          cd Plugins/
          git add .
          git commit -m "$GITHUB_JOB from $GITHUB_REPOSITORY
          git push https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/LaBoulangerie/Plugins.git HEAD:master
